/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author MastodonteEngasgado
 */
public class IUCadastroLivro extends javax.swing.JDialog {

    /**
     * Creates new form IUCadastroLivro
     */
    public IUCadastroLivro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.msg_aviso1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_codigo_livro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_codigo_livro = new javax.swing.JTextArea();
        botao_salvar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();
        label_nome = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto_nome = new javax.swing.JTextArea();
        label_ano = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto_ano = new javax.swing.JTextArea();
        msg_aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Livro");

        label_codigo_livro.setText("Codigo do Livro");

        texto_codigo_livro.setColumns(20);
        texto_codigo_livro.setRows(5);
        texto_codigo_livro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto_codigo_livroFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(texto_codigo_livro);

        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Cancelar");

        label_nome.setText("Nome");

        texto_nome.setColumns(20);
        texto_nome.setRows(5);
        jScrollPane2.setViewportView(texto_nome);

        label_ano.setText("Ano");

        texto_ano.setColumns(20);
        texto_ano.setRows(5);
        jScrollPane3.setViewportView(texto_ano);

        msg_aviso1.setForeground(new java.awt.Color(255, 0, 0));
        msg_aviso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg_aviso1.setText("Livro Já Cadastrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nome)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label_codigo_livro, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label_ano)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(botao_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_aviso1)
                        .addGap(97, 97, 97)
                        .addComponent(botao_cancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_codigo_livro)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nome)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_ano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_salvar)
                    .addComponent(botao_cancelar)
                    .addComponent(msg_aviso1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        // TODO add your handling code here:
        String codigo = texto_codigo_livro.getText();
        String nome = texto_nome.getText();
        int ano = Integer.parseInt(texto_ano.getText());
        Bibliotec.cadastrarLivro(codigo, nome, ano);
        this.dispose();
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void texto_codigo_livroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto_codigo_livroFocusLost
        String codigo = texto_codigo_livro.getText();
        Livro livro = Bibliotec.buscaLivro(codigo);
        if(livro != null){
            texto_nome.setText(livro.getNome());
            texto_ano.setText(Integer.toString(livro.getAno()));
            botao_salvar.setEnabled(false);
            this.msg_aviso1.setVisible(true);
        }
        else{
         texto_nome.setText("");
         texto_ano.setText("");
         botao_salvar.setEnabled(true);
         this.msg_aviso1.setVisible(false);
        }
    }//GEN-LAST:event_texto_codigo_livroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroLivro dialog = new IUCadastroLivro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_ano;
    private javax.swing.JLabel label_codigo_livro;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel msg_aviso1;
    private javax.swing.JTextArea texto_ano;
    private javax.swing.JTextArea texto_codigo_livro;
    private javax.swing.JTextArea texto_nome;
    // End of variables declaration//GEN-END:variables
}
