/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Pão De Forma
 */
public class IUCadastroAluno extends javax.swing.JDialog {

    /**
     * Creates new form IUCadastroAluno
     */
    public IUCadastroAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.msg_aviso1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_codigo_aluno = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_curso = new javax.swing.JLabel();
        label_ano = new javax.swing.JLabel();
        texto_codigo_aluno = new javax.swing.JTextField();
        texto_nome = new javax.swing.JTextField();
        texto_curso = new javax.swing.JTextField();
        texto_ano = new javax.swing.JTextField();
        botao_salvar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();
        msg_aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Aluno");

        label_codigo_aluno.setText("Código do Aluno");

        label_nome.setText("Nome");

        label_curso.setText("Curso");

        label_ano.setText("Ano");

        texto_codigo_aluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto_codigo_alunoFocusLost(evt);
            }
        });

        texto_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_cursoActionPerformed(evt);
            }
        });

        botao_salvar.setText("Salvar");
        botao_salvar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                botao_salvarFocusLost(evt);
            }
        });
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Cancelar");
        botao_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cancelarActionPerformed(evt);
            }
        });

        msg_aviso1.setForeground(new java.awt.Color(255, 0, 0));
        msg_aviso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg_aviso1.setText("Usuário Já Cadastrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label_codigo_aluno)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_nome)
                                .addGap(69, 69, 69)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(texto_codigo_aluno)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_curso)
                        .addGap(68, 68, 68)
                        .addComponent(texto_curso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_ano)
                        .addGap(77, 77, 77)
                        .addComponent(texto_ano))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botao_salvar)
                        .addGap(78, 78, 78)
                        .addComponent(msg_aviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(botao_cancelar)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_codigo_aluno)
                    .addComponent(texto_codigo_aluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(texto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_curso)
                    .addComponent(texto_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_ano)
                    .addComponent(texto_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_salvar)
                    .addComponent(msg_aviso1)
                    .addComponent(botao_cancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        String codigo = texto_codigo_aluno.getText();
        String nome = texto_nome.getText();
        String curso = texto_curso.getText();
        int ano = Integer.parseInt(texto_ano.getText());
        Bibliotec.cadastrarAluno(codigo, nome, curso, ano);
        this.dispose();
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void botao_salvarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botao_salvarFocusLost

    }//GEN-LAST:event_botao_salvarFocusLost

    private void texto_codigo_alunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto_codigo_alunoFocusLost
            String codigo = texto_codigo_aluno.getText();
        Usuario usuario = Bibliotec.buscaUsuario(codigo);
        if(usuario != null){
            texto_nome.setText(usuario.getNome());
            texto_curso.setText(usuario.getCurso());
            texto_ano.setText(Integer.toString(usuario.getAno()));
            botao_salvar.setEnabled(false);
            this.msg_aviso1.setVisible(true);
        }
        else{
            texto_nome.setText("");
            texto_curso.setText("");
            texto_ano.setText("");
            botao_salvar.setEnabled(true);
            this.msg_aviso1.setVisible(false);
        } 
    }//GEN-LAST:event_texto_codigo_alunoFocusLost

    private void texto_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_cursoActionPerformed

    private void botao_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroAluno dialog = new IUCadastroAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JLabel label_ano;
    private javax.swing.JLabel label_codigo_aluno;
    private javax.swing.JLabel label_curso;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel msg_aviso1;
    private javax.swing.JTextField texto_ano;
    private javax.swing.JTextField texto_codigo_aluno;
    private javax.swing.JTextField texto_curso;
    private javax.swing.JTextField texto_nome;
    // End of variables declaration//GEN-END:variables
}
