/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Pão De Forma
 */
public class IUCadastroProfessor extends javax.swing.JDialog {

    /**
     * Creates new form IUCadastroProfessor
     */
    public IUCadastroProfessor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.msg_aviso1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        label_codigo_professor = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_titulacao = new javax.swing.JLabel();
        botao_salvar = new javax.swing.JButton();
        botao_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_codigo_professor = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto_nome = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        texto_titulacao = new javax.swing.JTextArea();
        msg_aviso1 = new javax.swing.JLabel();

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Professor");

        label_codigo_professor.setText("Código do Professor");

        label_nome.setText("Nome");

        label_titulacao.setText("Titulação");

        botao_salvar.setText("Salvar");
        botao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_salvarActionPerformed(evt);
            }
        });

        botao_cancelar.setText("Cancelar");

        texto_codigo_professor.setColumns(20);
        texto_codigo_professor.setRows(5);
        texto_codigo_professor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto_codigo_professorFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(texto_codigo_professor);

        texto_nome.setColumns(20);
        texto_nome.setRows(5);
        jScrollPane2.setViewportView(texto_nome);

        texto_titulacao.setColumns(20);
        texto_titulacao.setRows(5);
        jScrollPane5.setViewportView(texto_titulacao);

        msg_aviso1.setForeground(new java.awt.Color(255, 0, 0));
        msg_aviso1.setText("Usuário Já Cadastrado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nome)
                    .addComponent(label_codigo_professor)
                    .addComponent(label_titulacao)
                    .addComponent(botao_salvar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_aviso1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(botao_cancelar))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_codigo_professor)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_titulacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_salvar)
                    .addComponent(botao_cancelar)
                    .addComponent(msg_aviso1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_salvarActionPerformed
        String codigo = texto_codigo_professor.getText();
        String nome = texto_nome.getText();
        String titulacao = texto_titulacao.getText();
        Bibliotec.cadastrarProfessor(codigo, nome, titulacao);
        this.dispose();
    }//GEN-LAST:event_botao_salvarActionPerformed

    private void texto_codigo_professorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto_codigo_professorFocusLost
        String codigo = texto_codigo_professor.getText();
        Usuario usuario = Bibliotec.buscaUsuario(codigo);
        if(usuario != null){
            texto_nome.setText(usuario.getNome());
            texto_titulacao.setText(usuario.getTitulacao());
            botao_salvar.setEnabled(false);
            this.msg_aviso1.setVisible(true);
        }
        else{
            texto_nome.setText("");
            texto_titulacao.setText("");
            botao_salvar.setEnabled(true);
            this.msg_aviso1.setVisible(false);
        }
    }//GEN-LAST:event_texto_codigo_professorFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroProfessor dialog = new IUCadastroProfessor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_cancelar;
    private javax.swing.JButton botao_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel label_codigo_professor;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_titulacao;
    private javax.swing.JLabel msg_aviso1;
    private javax.swing.JTextArea texto_codigo_professor;
    private javax.swing.JTextArea texto_nome;
    private javax.swing.JTextArea texto_titulacao;
    // End of variables declaration//GEN-END:variables
}
