/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Pão De Forma
 */
public class IURelatorioEspecifico extends javax.swing.JDialog {

    /**
     * Creates new form IURelatorioEspecifico
     */
    public IURelatorioEspecifico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        botao_selecionar.setEnabled(false);
        label_aviso1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        label_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_codigo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        texto_nome = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto_tipo = new javax.swing.JTextArea();
        label_codigo = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_tipo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        texto_relatorio = new javax.swing.JTextArea();
        botao_selecionar = new javax.swing.JButton();
        botao_limpar = new javax.swing.JButton();
        label_aviso1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio Especifico");

        label_titulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_titulo.setText("Relatorio");

        texto_codigo.setColumns(20);
        texto_codigo.setRows(5);
        texto_codigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                texto_codigoFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(texto_codigo);

        texto_nome.setEditable(false);
        texto_nome.setColumns(20);
        texto_nome.setRows(5);
        jScrollPane2.setViewportView(texto_nome);

        texto_tipo.setEditable(false);
        texto_tipo.setColumns(20);
        texto_tipo.setRows(5);
        jScrollPane3.setViewportView(texto_tipo);

        label_codigo.setText("Código do Usuário");

        label_nome.setText("Nome do Usuário");

        label_tipo.setText("Tipo do Usuário");

        texto_relatorio.setColumns(20);
        texto_relatorio.setRows(5);
        jScrollPane4.setViewportView(texto_relatorio);

        botao_selecionar.setText("Selecionar");
        botao_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_selecionarActionPerformed(evt);
            }
        });

        botao_limpar.setText("Limpar");

        label_aviso1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_aviso1.setForeground(new java.awt.Color(255, 0, 0));
        label_aviso1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_aviso1.setText("Usuário Inexistente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(label_titulo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botao_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_aviso1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(botao_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tipo))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botao_limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botao_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(label_aviso1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_codigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_texto_codigoFocusLost
        String codigo = texto_codigo.getText();
        Usuario usuario = Bibliotec.buscaUsuario(codigo);
        if(usuario == null){
            texto_nome.setText("");
            texto_tipo.setText("");
            botao_selecionar.setEnabled(false);
            label_aviso1.setVisible(true);
            
        }
        else{
            label_aviso1.setVisible(false);
            texto_nome.setText(usuario.getNome());
            texto_tipo.setText(usuario.getTipo());
            botao_selecionar.setEnabled(true);
        }
    }//GEN-LAST:event_texto_codigoFocusLost

    private void botao_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_selecionarActionPerformed
        String codigo = texto_codigo.getText();
        texto_relatorio.setText(Bibliotec.relatorioLivrosUsuario(codigo));
    }//GEN-LAST:event_botao_selecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IURelatorioEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IURelatorioEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IURelatorioEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IURelatorioEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IURelatorioEspecifico dialog = new IURelatorioEspecifico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_limpar;
    private javax.swing.JButton botao_selecionar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_aviso1;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_tipo;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTextArea texto_codigo;
    private javax.swing.JTextArea texto_nome;
    private javax.swing.JTextArea texto_relatorio;
    private javax.swing.JTextArea texto_tipo;
    // End of variables declaration//GEN-END:variables
}
